// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"go_zero_sample/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RequestDurationLoggerMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/id/:userId",
					Handler: GetUserHandler(serverCtx),
				},
			}...,
		),
	)
}
